Learning Tensorflow

2023.3

Import packages: 

Math example in Jupyter: $\alpha, \beta, \int_{}xdx, \sum_{i=1}^{10}x_{i}$

In [65]:
import tensorflow as tf
import numpy as np

Creating Variables:

In [34]:
s=tf.Variable("hi, what's up")
x=tf.Variable(114514)
y=tf.Variable(3.14159,tf.float32)
tensor1=tf.Variable(["In memoriam"],tf.string)
tensor2=tf.Variable([["wtf","tf",""],["2","4","43.4343"]],tf.string)

In [35]:
print(s)
print(x)
print(y)
print(tensor1)
print(tensor2)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b"hi, what's up">
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=114514>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.14159>
<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'In memoriam'], dtype=object)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=string, numpy=
array([[b'wtf', b'tf', b''],
       [b'2', b'4', b'43.4343']], dtype=object)>


Output:

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b"hi, what's up">

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=114514>

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.14159>

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'In memoriam'], dtype=object)>

<tf.Variable 'Variable:0' shape=(2,) dtype=string, numpy=array([b'wtf', b'tf'], dtype=object)>

In [36]:
print(s.shape)
print(tensor1.shape)
print(tensor2.shape)
print(tf.rank(s))
print(tf.rank(tensor1))
print(tf.rank(tensor2))

()
(1,)
(2, 3)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


Changing Variables

In [39]:
tensor3=tf.ones([1,2,3])
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [41]:
tensor3=tf.ones([3,6,8])
print(tensor3)

tf.Tensor(
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]], shape=(3, 6, 8), dtype=float32)


In [57]:
tensor3=tf.Variable([[5,2,3],[6,4,8]])
print(tensor3)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[5, 2, 3],
       [6, 4, 8]], dtype=int32)>


In [60]:
tensor3=tf.reshape(tensor3, [6])
print(tensor3)
tensor3=tf.reshape(tensor3, [1,-1])
print(tensor3)

tf.Tensor([5 2 3 6 4 8], shape=(6,), dtype=int32)
tf.Tensor([[5 2 3 6 4 8]], shape=(1, 6), dtype=int32)


Slicing Tensor

In [83]:
matrix=[[(i*i+(i*i*i)%10+4*j)%11 for i in range(5)] for j in range(4)]
print(matrix)
matrix=np.array(matrix)
print(matrix,"\nshape:",matrix.shape)

[[0, 2, 1, 5, 9], [4, 6, 5, 9, 2], [8, 10, 9, 2, 6], [1, 3, 2, 6, 10]]
[[ 0  2  1  5  9]
 [ 4  6  5  9  2]
 [ 8 10  9  2  6]
 [ 1  3  2  6 10]] 
shape: (4, 5)


In [84]:
matrx=tf.Variable(matrix)
print(matrx)
print(matrx.shape)

<tf.Variable 'Variable:0' shape=(4, 5) dtype=int64, numpy=
array([[ 0,  2,  1,  5,  9],
       [ 4,  6,  5,  9,  2],
       [ 8, 10,  9,  2,  6],
       [ 1,  3,  2,  6, 10]])>
(4, 5)


In [85]:
x1=matrx[0:2]
print(x1)

tf.Tensor(
[[0 2 1 5 9]
 [4 6 5 9 2]], shape=(2, 5), dtype=int64)


In [86]:
x2=matrx[2,3]
print(x2)

tf.Tensor(2, shape=(), dtype=int64)


In [96]:
x3=matrx[:,:]
print(x3)
x3=matrx[:,1]
print(x3)
x3=matrx[[2]]
print(x3)

tf.Tensor(
[[ 0  2  1  5  9]
 [ 4  6  5  9  2]
 [ 8 10  9  2  6]
 [ 1  3  2  6 10]], shape=(4, 5), dtype=int64)
tf.Tensor([ 2  6 10  3], shape=(4,), dtype=int64)
tf.Tensor([ 8 10  9  2  6], shape=(5,), dtype=int64)
